server:
  port: 9010

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://mysql:3306/seckill_account
    username: root
    password: root
  cloud:
    nacos:
      server-addr: nacos:8848
  redis:
    host: redis
    port: 6379
