server:
  port: 9010

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql:///seckill_account
    username: root
    password: root
  jpa:
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          seckill-service:
            url: http://localhost:9030
          mock-service:
            url: http://localhost:9040

