server:
  port: 9040

spring:
  application:
    name: mock-service
  datasource:
    url: jdbc:mysql://mysql:3306/seckill_mock
    username: root
    password: root
  cloud:
    nacos:
      server-addr: nacos:8848
