server:
  port: 9020

spring:
  application:
    name: seckill-payment-service
  datasource:
    url: jdbc:mysql:///seckill_payment_db
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

rocketmq:
  producer:
    group: cart-producer-group
  name-server: localhost:9876

management:
  endpoints:
    web:
      exposure:
        include: '*'
