server:
  port: 9020

spring:
  application:
    name: seckill-payment-service
  datasource:
    url: jdbc:mysql://payment-db:3306/seckill_payment_db
    username: root
    password: root
  redis:
    host: payment-redis
    port: 6379
  cloud:
    nacos:
      server-addr: nacos:8848
    stream:
      default-binder: rocketmq
      rocketmq:
        binder:
          name-server: rocketmq:9876
          group: default
      bindings:
        placeOrder-out-0:
          destination: order
        requestForPay-out-0:
          destination: pay
        orderHandle-in-0:
          destination: order
          group: order
          consumer:
            maxAttempts: 30
        payHandle-in-0:
          destination: pay
          group: pay
          consumer:
            maxAttempts: 30

    function:
      definition: orderHandle;payHandle
