server:
  port: 9020

spring:
  application:
    name: seckill-payment-service
  datasource:
    url: jdbc:mysql:///seckill_payment_db
    username: root
    password: root

rocketmq:
  producer:
    group: cart-producer-group
  name-server: localhost:9876

management:
  endpoints:
    web:
      exposure:
        include: '*'
