server:
  port: 9020

spring:
  application:
    name: seckill-payment-service
  datasource:
    url: jdbc:mysql:///seckill_payment_db
    username: root
    password: root
  redis:
      database: 1
  cloud:
    stream:
      default-binder: rocketmq
      rocketmq:
        binder:
          name-server: localhost:9876
          group: default
      bindings:
        placeOrder-out-0:
          destination: order
        requestForPay-out-0:
          destination: pay
        orderHandle-in-0:
          destination: order
          group: order
        payHandle-in-0:
          destination: pay
          group: pay

    function:
      definition: orderHandle;payHandle

management:
  endpoints:
    web:
      exposure:
        include: '*'
