server:
  port: 9001

spring:
  application:
    name: seckill-service
  datasource:
    url: jdbc:mysql:///seckill_system
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
