server:
  port: 81

spring:
  datasource:
    url: jdbc:mysql:///erupt?serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

erupt:
  dbs:
    -
      datasource:
        name: mysql_seckill_system
        url: jdbc:mysql:///seckill_system?serverTimezone=Asia/Shanghai
        username: root
        password: root

      jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        open-in-view: true
        database: mysql

      scanPackages: com.lingyuango.seckillmanagement.pojo
