server:
  port: 81

spring:
  datasource:
    url: jdbc:mysql://erupt-db:3306/erupt?serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

erupt:
  dbs:
      -
        datasource:
          name: mysql_seckill_service_db
          url: jdbc:mysql://seckill-db:3306/seckill_service_db?serverTimezone=Asia/Shanghai
          username: root
          password: root

        hikari:
          pool-name: erupt-mysql
          minimum-idle: 10
          maximum-pool-size: 100

        jpa:
          show-sql: true
          database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
          open-in-view: true
          database: mysql

        scanPackages: com.lingyuango.seckillmanagement.pojo

      -
        datasource:
          name: mysql_seckill_payment_db
          url: jdbc:mysql://payment-db:3306/seckill_payment_db?serverTimezone=Asia/Shanghai
          username: root
          password: root


        jpa:
            show-sql: true
            database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
            open-in-view: true
            database: mysql

        scanPackages: com.lingyuango.seckillmanagement.pojo
