server:
  port: 9000

spring:
  application:
    name: gateway
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      # 启动gateway
      discovery:
        locator:
          enabled: true

      # 配置全局跨域
      globalcors:
        cors-configurations:
          "[/**]":
            allow-credentials: true
            allowed-origin-patterns: "*"
            allowed-methods: GET, POST
            allowed-headers: "*"

      # 配置暴露路径
      routes:
        # 账号服务
        - id: account-service
          uri: http://account-service:9010
          predicates:
            - Path=/customer/**
          filters:
            - PreserveHostHeader

        # 秒杀服务
        - id: seckill-service
          uri: http://seckill-service:9030
          predicates:
            - Path=/seckillActivity/**
          filters:
            - PreserveHostHeader

