server:
  port: 9020

spring:
  application:
    name: seckill-payment-service
  datasource:
    url: jdbc:mysql:///seckill_payment_db
    username: root
    password: root
  redis:
      database: 1
  cloud:
    stream:
      bindings:
        placeOrder-out-0:
          destination: order
          group: order
        requestForPay-out-0:
          destination: pay
          group: pay
        orderHandle-in-0:
          destination: order
          group: order
          consumer:
            maxAttempts: 30
        payHandle-in-0:
          destination: pay
          group: pay
          consumer:
            maxAttempts: 30

    function:
      definition: orderHandle;payHandle
