server:
  port: 9040

spring:
  application:
    name: seckill-mock-service
  datasource:
    url: jdbc:mysql:///seckill_mock_db
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: '*'
