server:
  port: 9040

spring:
  application:
    name: seckill-mock-service
  datasource:
    url: jdbc:mysql://mock-db:3306/seckill_mock_db
    username: root
    password: root
  cloud:
    nacos:
      server-addr: nacos:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
