version: '3'

# Author: zwz15008, Jmc
# Need at least 4G memory
services:
  web:
    build: web
    restart: always
    ports:
      - '80:80'
      - '9000:9000'
    volumes:
      - ./web/conf/nginx.conf:/etc/nginx/nginx.conf

  # --------------------------------------------------------------- #

  nacos:
    image: nacos/nacos-server:v2.0.4
    restart: always
    environment:
      MODE: standalone
      JVM_XMS: 128M
      JVM_XMX: 128M
    ports:
      - '8848:8848'

  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3310:3306'
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/sql:/sql

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - '6379'

  rabbitmq:
    image: rabbitmq:3.9.15-management
    restart: always
    ports:
      - '5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  # --------------------------------------------------------------- #

  gateway:
    build: services/gateway
    restart: always
    ports:
      - '9000'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: nacos:8848, redis:6379
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  # --------------------------------------------------------------- #

  account-service:
    build: services/account
    restart: always
    ports:
      - '9010'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: nacos:8848, mysql:3306, redis:6379
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  # --------------------------------------------------------------- #

  payment-service:
    build: services/payment
    restart: always
    ports:
      - '9020'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: nacos:8848, mysql:3306, redis:6379, rabbitmq:5672
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  # --------------------------------------------------------------- #

  seckill-service:
    build: services/seckill
    restart: always
    ports:
      - '9030'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: nacos:8848, mysql:3306, redis:6379
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  # --------------------------------------------------------------- #

  mock-service:
    build: services/mock
    restart: always
    ports:
      - '9040'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: nacos:8848, mysql:3306
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  # --------------------------------------------------------------- #

  web-management:
    build: services/web-management
    restart: always
    ports:
      - '81:81'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

