version: "3"

# Author: zwz15008, Jmc
# Need at least 4G memory
# Version: 2.0
services:
  web:
    image: nginx:1.20.2
    restart: always
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - ./web/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./web/dist/:/usr/share/nginx/html/
  # --------------------------------------------------------------- #

  web-management:
    image: openjdk:17
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./bin/wait:/wait
      - ./services/web-management.jar:/app.jar
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    entrypoint:
      - /bin/sh
      - -c
      - /wait && java -jar /app.jar

  # --------------------------------------------------------------- #

  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/sql:/sql

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - "6379"

  rabbitmq:
    image: rabbitmq:3.9.15-management
    restart: always
    ports:
      - "5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  # --------------------------------------------------------------- #

  gateway:
    image: alpine:3.17.1
    restart: always
    ports:
      - "9000"
    volumes:
      - ./bin/wait:/wait
      - ./services/gateway:/app
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: redis:6379
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    entrypoint:
      - /bin/sh
      - -c
      - /wait && /app

  # --------------------------------------------------------------- #

  account-service:
    image: alpine:3.17.1
    restart: always
    ports:
      - "9010"
    volumes:
      - ./bin/wait:/wait
      - ./services/account:/app
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, redis:6379
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    entrypoint:
      - /bin/sh
      - -c
      - /wait && /app

  # --------------------------------------------------------------- #

  payment-service:
    image: alpine:3.17.1
    restart: always
    ports:
      - "9020"
    volumes:
      - ./bin/wait:/wait
      - ./services/payment:/app
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, redis:6379, rabbitmq:5672
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    entrypoint:
      - /bin/sh
      - -c
      - /wait && /app

  # --------------------------------------------------------------- #

  seckill-service:
    image: alpine:3.17.1
    restart: always
    ports:
      - "9030"
    volumes:
      - ./bin/wait:/wait
      - ./services/seckill:/app
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, redis:6379
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    entrypoint:
      - /bin/sh
      - -c
      - /wait && /app

  # --------------------------------------------------------------- #

  mock-service:
    image: alpine:3.17.1
    restart: always
    ports:
      - "9040"
    volumes:
      - ./bin/wait:/wait
      - ./services/mock:/app
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    entrypoint:
      - /bin/sh
      - -c
      - /wait && /app

