version: '3'

# Need at least 4G memory + 2G swap
services:
  web:
    build: web
    restart: always
    ports:
      - '80:80'
      - '9010:9010'
      - '9020:9020'
      - '9030:9030'
      - '9040:9040'
    volumes:
      - ./web/conf/nginx.conf:/etc/nginx/nginx.conf

  web-management:
    build: services/web-management
    restart: always
    ports:
      - '81:81'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: erupt-db:3306, seckill-db:3306, payment-db:3306
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  account-service-1:
    build: services/account-service
    restart: always
    ports:
      - '9010'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: account-db:3306, seckill-redis:6379, nacos:8848
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  account-service-2:
    build: services/account-service
    restart: always
    ports:
      - '9010'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: account-service-1:9010
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  payment-service-1:
    build: services/payment-service
    restart: always
    ports:
      - '9020'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: payment-db:3306, payment-redis:6379, rabbitmq:5672, nacos:8848
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  payment-service-2:
    build: services/payment-service
    restart: always
    ports:
      - '9020'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: payment-service-1:9020
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  seckill-service-1:
    build: services/seckill-service
    restart: always
    ports:
      - '9030'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: seckill-db:3306, seckill-redis:6379, nacos:8848
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  seckill-service-2:
    build: services/seckill-service
    restart: always
    ports:
      - '9030'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: seckill-service-1:9030
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  mock-service-1:
    build: services/mock-service
    restart: always
    ports:
      - '9040'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mock-db:3306, nacos:8848
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  mock-service-2:
    build: services/mock-service
    restart: always
    ports:
      - '9040'
    volumes:
      - ./bin/wait:/wait
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mock-service-1:9040
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10

  account-db:
    image: mysql:8.0.28
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seckill_account_db
    ports:
      - '3306'
    volumes:
      - ./mysql/account-db:/docker-entrypoint-initdb.d

  mock-db:
    image: mysql:8.0.28
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seckill_mock_db
    ports:
      - '3306'
    volumes:
      - ./mysql/mock-db:/docker-entrypoint-initdb.d

  payment-db:
    image: mysql:8.0.28
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seckill_payment_db
    ports:
      - '3306'
    volumes:
      - ./mysql/payment-db:/docker-entrypoint-initdb.d

  seckill-db:
    image: mysql:8.0.28
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seckill_service_db
    ports:
      - '3306'
    volumes:
      - ./mysql/seckill-db:/docker-entrypoint-initdb.d

  erupt-db:
      image: mysql:8.0.28
      restart: always
      environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: erupt
      ports:
        - '3306'
      volumes:
        - ./mysql/erupt-db:/docker-entrypoint-initdb.d

  seckill-redis:
    image: redis:6.2.6
    restart: always
    ports:
      - '6379'

  payment-redis:
    image: redis:6.2.6
    restart: always
    ports:
      - '6379'

  rabbitmq:
    image: rabbitmq:3.9.15-management
    restart: always
    ports:
      - '5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  nacos:
    image: nacos/nacos-server:v2.0.4
    restart: always
    environment:
      MODE: standalone
      JVM_XMS: 128M
      JVM_XMX: 128M
    ports:
      - '8848:8848'
