server:
  port: 9030

spring:
  application:
    name: seckill-service
  datasource:
    url: jdbc:mysql:///seckill_service
    username: root
    password: root
  jpa:
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          account-service:
            url: http://localhost:9010
          payment-service:
            url: http://localhost:9020

