server:
  port: 9030

spring:
  application:
    name: seckill-service
  datasource:
    url: jdbc:mysql://mysql:3306/seckill_service
    username: root
    password: root
  cloud:
    nacos:
      server-addr: nacos:8848
  redis:
    host: redis
    port: 6379

