server:
  port: 9030

spring:
  application:
    name: seckill-service
  datasource:
    url: jdbc:mysql://mysql:3306/seckill_service
    username: root
    password: root
  cloud:
    openfeign:
      client:
        config:
          account-service:
            url: http://account-service:9010
          payment-service:
            url: http://payment-service:9020
  data:
    redis:
      host: redis
      port: 6379

