server:
  port: 9020

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://mysql:3306/seckill_payment
    username: root
    password: root
  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
  data:
    redis:
      host: redis
      port: 6379
      database: 1
  cloud:
    openfeign:
      client:
        config:
          account-service:
            url: http://account-service:9010
          seckill-service:
            url: http://seckill-service:9030
          mock-service:
            url: http://mock-service:9040
    stream:
      bindings:
        placeOrder-out-0:
          destination: order
          group: order
        requestForPay-out-0:
          destination: pay
          group: pay
        orderHandle-in-0:
          destination: order
          group: order
          consumer:
            maxAttempts: 30
        payHandle-in-0:
          destination: pay
          group: pay
          consumer:
            maxAttempts: 30

    function:
      definition: orderHandle;payHandle
