server:
  port: 9010

spring:
  application:
    name: seckill-account-service
  datasource:
    url: jdbc:mysql://account-db:3306/seckill_account_db
    username: root
    password: root
  cloud:
    nacos:
      server-addr: nacos:8848
  redis:
    host: seckill-redis
    port: 6379
