server:
  port: 9001

spring:
  application:
    name: seckill-account-service
  datasource:
    url: jdbc:mysql:///seckill_account_db
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: '*'
